// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfKdqWXO9QLpxxmikNPVlaUe33YlPc-Bo',
    appId: '1:548062254881:web:faf7574a7b8a81b9d91060',
    messagingSenderId: '548062254881',
    projectId: 'chatapp-42274',
    authDomain: 'chatapp-42274.firebaseapp.com',
    storageBucket: 'chatapp-42274.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOfNBWKL9DDSPsBTXAVFBMSSBbgaNH2ek',
    appId: '1:548062254881:android:c10bfbb1416767ebd91060',
    messagingSenderId: '548062254881',
    projectId: 'chatapp-42274',
    storageBucket: 'chatapp-42274.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjY4G08biXBy_w5dNKr_3Hvna1xeQ_6mE',
    appId: '1:548062254881:ios:160afa293bd25ba8d91060',
    messagingSenderId: '548062254881',
    projectId: 'chatapp-42274',
    storageBucket: 'chatapp-42274.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
